version: '2'

services:
    node:
        container_name: node-sandbox
        build:
            context: .
            dockerfile: .docker/node.dockerfile
        volumes:
            - ./api:/home/api/
            - /home/api/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            
    angular: # name of the first service
        build:
            context: .
            dockerfile: .docker/angular.dockerfile
        volumes:
            - ./client:/home/client/
            - /home/client/node_modules
            - /home/client/typings
        ports: 
            - '4200:4200' # specify port forwarding
    mongo:
        container_name: mongo-sandbox
        build:
            context: .
            dockerfile: .docker/mongo.dockerfile
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
networks:
    sandbox-network:
        driver: bridge
