version: '2'

services:
    node:
        container_name: sandbox
        build:
            context: .
            dockerfile: node.dockerfile
        ports:
            - "3000:3000"
    mongo:
        container_name: mongo-sandbox
        build:
            context: .
            dockerfile: mongo.dockerfile
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
networks:
    sandbox-network:
        driver: bridge
