version: '2'

services:
    node:
        container_name: node-sandbox
        build:
            context: .
            dockerfile: .docker/node.dockerfile
        volumes:
            - .:/home/app/
            - /home/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - mongo
    mongo:
        container_name: mongo-sandbox
        build:
            context: .
            dockerfile: .docker/mongo.dockerfile
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
networks:
    sandbox-network:
        driver: bridge
